describe('Ejecutar juego', () => {
  it('Perder por errores', () => {
    cy.visit('/')
    cy.contains('Jugar').click()
    cy.url().should('include', '/game')
    cy.get('#levels').select('Facil')
    cy.get('.bg-red-3003 > .w-6').click()
    cy.contains('Iniciar juego').click()
    cy.get('.letters > :nth-child(1)').click()
    cy.get('.letters > :nth-child(2)').click()
    cy.get('.letters > :nth-child(3)').click()
    cy.get('.letters > :nth-child(4)').click()
    cy.get('.letters > :nth-child(5)').click()
    cy.get('.letters > :nth-child(7)').click()
    cy.get('.letters > :nth-child(8)').click()
    cy.get('.letters > :nth-child(9)').click()
    cy.contains('Perdiste , vuelve a intentarlo')
  })
})