name: Arrancar el servidor
run-name: Arrancando el servidor
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      # - run : cd web
      # - run: pwd
      # - run: ls
      # - run : cd /web
      - run: npm install --no-audit --no-optional --no-fund
      # - run: yarn dev
      - name : Ejecutar ESLINT para ver errores de codigo...
        run: yarn lint
      - name : Ejecutar los Tests...
        run: |
          yarn test
          yarn coverage
  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/Lucho/GitHub/Agiles/agiles-front
            git pull
            yarn
            yarn buildActions 
            cp -r /root/Lucho/GitHub/Agiles/agiles-front/dist/* /var/www/Lucho-Dev/Agiles
          


# Saco este test por ahora  yarn test:e2e