name: Arrancar el servidor
run-name: Arrancando el servidor
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Tests_Compile_Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install --no-audit --no-optional --no-fund
      # - name : Ejecutar ESLINT para ver errores de codigo...
      #   run: yarn lint
      - name : Punto 3 - Compilar el proyecto...
        run: yarn buildActions
      - name : Punto 4 - Ejecutar los Unit Test...
        run: |
          yarn test
      - name : Punto 5 - Code coverage...
        run: |
          yarn coverage
      - name: Punto 7 - Deploy en el servidor...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/Lucho/GitHub/Agiles/agiles-front
            git restore .
            git pull
            yarn
            yarn buildActions 
            rm -r /var/www/test/*
            cp -r /root/Lucho/GitHub/Agiles/agiles-front/dist/* /var/www/test

# Saco este test por ahora  yarn test:e2e